local:
    CLIENT_ID:
    PERSONAL_ACCESS_TOKEN:
    OAUTH_SCOPES: osf.full_read osf.full_write
stage:
    CLIENT_ID: 748efee9cec142e1afbb0638d5ab6898
    PERSONAL_ACCESS_TOKEN: v1kJZD8UWQd8r6jvV6XIlbseb1R6PRKay3avWaFX
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://localhost:4200/
